name: Pull Request Test

on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: write
  pull-requests: write
  checks: write

jobs:
  pr:
    name: Pull Request Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache
          key: ${{ runner.os }}

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm




      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build











        run: npm run ci:e2e-tests

      - name: Upload End to End Test Images
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: e2e-tests/test/__image_snapshots__/

            
            
